### ISSUE TITLE
Ability to specify channel

### ISSUE THREAD

**Issue by nomeelnoj** [innocarpe/actions-slack#2]
Hey Innocarpe!

This action is definitely one of my favorites when it comes to slack notifications, but I feel that it is lacking in one key area: the ability to specify a slack channel.  Many other actions that simply use a webhook allow for this customization.

While I do not know typescript and do not want to offend you with a lousy PR, I was looking around and I think that something like this might work:

```
this.webhook = new IncomingWebhook(process.env.SLACK_WEBHOOK_URL, {
      channel: 'process.env.SLACK_CHANNEL',
    })
```

Thanks in advance!

**Comment by innocarpe** [comment]
Hi @nomeelnoj, you would select the specific slack channel when you set up a incoming webhook for this action! (In you app from [Slack API](https://api.slack.com/apps).

As described in `README.md`, you can use like below after setting it up to GitHub secret in your repo.

```yaml
- name: Notify
  uses: innocarpe/actions-slack@v1
  with:
    status: ${{ job.status }} # Required
    success_text: 'Step Succeeded 🚀' # Optional
    ...
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required
    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Required
```

Hope this would help 😇
