### ISSUE TITLE
Issue with "status" not recognized by GH actions

### ISSUE THREAD

**Issue by bencalegari** [innocarpe/actions-slack#4]
We're using this action on our deploys and I just noticed the following warning within the github action UI:

```
Check warning on line 1 in .github

@github-actions
github-actions
/ Deploy to Aptible staging

.github#L1
Unexpected input(s) 'status', valid inputs are ['success_text', 'failure_text', 'cancelled_text']
```

Here's how we've set up the action:
```
      - name: Announce on Slack
        if: ${{ always() }}
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: 'Deploy to Aptible staging succeeded :smile:'
          failure_text: 'Deploy to Aptible staging failed :frowning:'
```

Although the line it's warning about is wrong, it does appear that the warning is coming from this package. Any idea why it's not recognizing the `status` key? To be clear, the Slack notifications are otherwise working as expected.
